name: Media Library Cleanup

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  NEXT_CLOUDINARY_CLOUDINARY_CLOUD_NAME: ${{ secrets.NEXT_CLOUDINARY_CLOUDINARY_CLOUD_NAME }}
  NEXT_CLOUDINARY_CLOUDINARY_API_KEY: ${{ secrets.NEXT_CLOUDINARY_CLOUDINARY_API_KEY }}
  NEXT_CLOUDINARY_CLOUDINARY_API_SECRET: ${{ secrets.NEXT_CLOUDINARY_CLOUDINARY_API_SECRET }}

  SPACEJELLY_TUTORIALS_CLOUDINARY_CLOUD_NAME: ${{ secrets.SPACEJELLY_TUTORIALS_CLOUDINARY_CLOUD_NAME }}
  SPACEJELLY_TUTORIALS_CLOUDINARY_API_KEY: ${{ secrets.SPACEJELLY_TUTORIALS_CLOUDINARY_API_KEY }}
  SPACEJELLY_TUTORIALS_CLOUDINARY_API_SECRET: ${{ secrets.SPACEJELLY_TUTORIALS_CLOUDINARY_API_SECRET }}

  COLBYCLOUD_MEDIA_JAMS_CLOUDINARY_CLOUD_NAME: ${{ secrets.MEDIA_JAMS_CLOUDINARY_CLOUD_NAME }}
  COLBYCLOUD_MEDIA_JAMS_CLOUDINARY_API_KEY: ${{ secrets.MEDIA_JAMS_CLOUDINARY_API_KEY }}
  COLBYCLOUD_MEDIA_JAMS_CLOUDINARY_API_SECRET: ${{ secrets.MEDIA_JAMS_CLOUDINARY_API_SECRET }}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: yarn install --frozen-lockfile

      - run: node src/media-library-cleanup.js